changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Security
      labels:
        - security
    - title: Compiler and runtime
      labels:
        - compiler
        - runtime
    - title: Adapters and exporters
      labels:
        - adapter
        - exporter
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
    - title: Other changes
      labels:
        - "*"
