(data_only_dirs .github)

(alias
 (name test-fast)
 (deps
  (alias test/fast)))

(alias
 (name test-contract)
 (deps
  (alias test/contract)))

(alias
 (name test-platform)
 (deps
  (alias test/platform)))

(alias
 (name test-differential)
 (deps
  (alias test/differential)))

(alias
 (name test-security)
 (deps
  (alias test/security)))

(alias
 (name test-all)
 (deps
  (alias test-fast)
  (alias test-contract)
  (alias test-platform)
  (alias test-differential)
  (alias test-security)))

(alias
 (name runtest)
 (deps
  (alias test-all)))
