(rule
 (targets
  (dir cargo-target))
 (deps
  Cargo.toml
  Cargo.lock
  (source_tree src))
 (action
  (run
   cargo
   build
   --locked
   --release
   --manifest-path
   Cargo.toml
   --target-dir
   cargo-target)))

(install
 (package de-shell)
 (section libexec)
 (files
  (cargo-target/release/deshell-nushell-adapter%{ext_exe}
   as
   deshell-nushell-adapter.exe)))
